### ISSUE TITLE
nim repo CI fails cause by Measuremancer has ambiguous call

### ISSUE THREAD

**Issue by bung87** [SciNim/Measuremancer#2]
/home/runner/.nimble/pkgs/measuremancer-0.1.1/measuremancer.nim(280, 15) Error: ambiguous call; both measuremancer.*(m: Measurement[*.U], x: T: FloatLike) [proc declared in /home/runner/.nimble/pkgs/measuremancer-0.1.1/measuremancer.nim(262, 6)] and measuremancer.*(m: Measurement[*.T], x: T: FloatLike) [proc declared in /home/runner/.nimble/pkgs/measuremancer-0.1.1/measuremancer.nim(265, 6)] match for: (T, float)  

I dont see recent changes in nim related to this, could you take a look?

**Comment by Vindaar** [comment]
Yup, I already saw it here https://github.com/nim-lang/Nim/pull/20593#issuecomment-1283556651 but thanks for the issue! Looking into it right now.
